apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-29T16:44:53.794580
    commit.image.appsody.dev/date: Tue Jul 28 15:43:52 2020 +0530
    commit.image.appsody.dev/message: changing the defaults
    commit.stack.appsody.dev/contextDir: /incubator/java-openliberty
    commit.stack.appsody.dev/date: Thu May 14 09:37:35 2020 +0100
    commit.stack.appsody.dev/message: 'Merge pull request #340 from groeges/release-0.9-codewind'
    description: This image is the Kabanero development container for the java-openliberty
      stack
    distribution-scope: public
    image.opencontainers.org/created: "2020-07-28T15:56:41+05:30"
    image.opencontainers.org/documentation: https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty
    image.opencontainers.org/revision: 8e296cbedac2b453d0efced8cbe1ecda51ae2f19-modified
    image.opencontainers.org/source: https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty/tree/hp-fixes
    image.opencontainers.org/url: https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-openliberty
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1002.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "277"
    stack.appsody.dev/authors: Mike Andrasak <uberskigeek>, Andy Mauer <ajm01>, Scott
      Kurz <>, Adam Wisniewski <>
    stack.appsody.dev/configured: docker.io/kabanero/java-openliberty:0.2
    stack.appsody.dev/created: "2020-05-19T06:42:46Z"
    stack.appsody.dev/description: Open Liberty & OpenJ9 using Maven
    stack.appsody.dev/digest: sha256:159e690d3a8caf113e7cebb7f30195b680b65b84148dc31df06a2632481880fb
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 104bb146d0d770e30886b845d7fca9311d54ed20
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty/image
    stack.appsody.dev/tag: docker.io/kabanero/java-openliberty:0.2.3
    stack.appsody.dev/title: Open Liberty
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty
    summary: Image for Kabanero java-openliberty development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-277
    vcs-ref: c42933bcdbf9f1c232e981a5e40de257c3534c8e
    vcs-type: git
    vendor: Kabanero
    version: 0.2.3
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: inventory-ms-openliberty
    stack.appsody.dev/id: java-openliberty
    stack.appsody.dev/version: 0.2.3
  name: inventory-ms-openliberty
spec:
  applicationImage: dev.local/inventory-ms-openliberty
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-openliberty
  version: 1.0.0
